USE master;
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'Pa$$w0rd';
GO

CREATE CERTIFICATE BankingAppCert
WITH SUBJECT = 'Banking App Encryption Certificate';
GO

BACKUP CERTIFICATE BankingAppCert
TO FILE = 'C:\SQLCerts\BankingAppCert.cert'
WITH PRIVATE KEY (
    FILE = 'C:\SQLCerts\BankingAppCert.key',
    ENCRYPTION BY PASSWORD = 'Pa$$w0rd'
);
GO

USE [BankingAppDB];
GO
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE BankingAppCert;
GO

ALTER DATABASE [BankingAppDB] SET ENCRYPTION ON;
GO